sidebar_details: |
  The system will process, chunk, and embed your files for quick retrieval,
  then generate accurate answers using an AI model.  
  Simply upload, ask, and explore insights all in one place.  